# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Gradle Package

# on:
#   release:
#     types: [created]

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current

    - name: Package with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: packageReleaseUberJarForCurrentOS
        gradle-version: current

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/compose/jars/*.jar
